version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .      # Dockerfile folder path
    # ports:              #no more used because "nginx" container
    #   - "3000:3000"
    environment:
      - PORT=3000
    depends_on: 
      - mongo
  
  mongo:
    image: mongo:4.4.18
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alb
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  

  redis:
    image: redis



volumes:          # common volumes
  mongo-db: