version: "3"
services:
  nginx:
    ports:
      - "80:80"
 
  node-app:
    deploy:
      replicas: 8                           # replicate 8 times the nod-app containers to scale it up
      restart_policy:
        condition: any
      update_config:                        # update 2 by 2
        parallelism: 2
        delay: 15s

    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js
  mongo:                                            #overrides the compose.yml
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}